### ISSUE TITLE
Implementing divolteStream usign DirectStream API

### ISSUE THREAD

**Issue by fnozarian** [divolte/divolte-collector#134] opened 2016-09-06 05:35 UTC
Hello.
I noticed that the `divolteStream` uses `createStream` method of `KafkaUtils` to establish a stream, however since Spark 1.3 it is recomended to use [DirectStream API](http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.streaming.kafka.KafkaUtils$@createDirectStream[K,V,KD<:kafka.serializer.Decoder[K],VD<:kafka.serializer.Decoder[V]](jssc:org.apache.spark.streaming.api.java.JavaStreamingContext,keyClass:Class[K],valueClass:Class[V],keyDecoderClass:Class[KD],valueDecoderClass:Class[VD],kafkaParams:java.util.Map[String,String],topics:java.util.Set[String]):org.apache.spark.streaming.api.java.JavaPairInputDStream[K,V]) (`createDirectStream`) to read data from Kafka. Do you have any plan to re-implement `divolteStream` using this API?

**Comment by asnare** [comment] 2016-09-06 19:38
This is a duplicate of divolte/divolte-spark#1.

**Closed by asnare** 2016-09-06 19:38 UTC
Labels: duplicate
